divein/urls.py
from django.conf.urls import patterns, url

from divein import views

urlpatterns = patterns('',
	url(r'^$'             		 , views.index						 , name='index'),
    url(r'^divers/$'             , views.DiverListView.as_view()     , name='divers'),
    url(r'^diver/(?P<pk>\d+)/$'  , views.DiverDetailView.as_view()   , name='diver'),
    url(r'^profile/$'            , views.profile                     , name='profile'),
    url(r'^dive/(?P<pk>\d+)/$'   , views.dive_detail    			 , name='dive'),
    url(r'^dive/add/$'           , views.dive_form                   , name='dive_add'),
    url(r'^spot/(?P<pk>\d+)/$'   , views.SpotDetailView.as_view()    , name='spot'),
    url(r'^spots$'               , views.SpotListView.as_view()      , name='spots'),
    url(r'^spot/(?P<pk>\d+)/dive_add$'   , views.spot_add_dive       , name='spot_add_dive'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'divein/login.html'}, name='login'),
    url(r'^logout$'               , views.logoutv                    , name='logout'),
    # url(r'^dive/(?P<pk>\d+)/$'   , views.DiveDetailView.as_view()    , name='dive'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from polls.models import Poll
from polls.models import Choice

# admin.site.register(Choice)

class ChoiceInline(admin.TabularInline):
    model = Choice
    extra = 3

class PollAdmin(admin.ModelAdmin):
    fieldsets = [
        (None,               {'fields': ['question']}),
        ('Date information', {'fields': ['pub_date'], 'classes': ['collapse']}),
    ]
    #What to display?
    list_display = ('question', 'pub_date', 'was_published_recently')
    #How to display Choices?
    inlines = [ChoiceInline]

    list_filter     = ['pub_date']
    search_fields   = ['question']
    date_hierarchy  = 'pub_date'

admin.site.register(Poll, PollAdmin)

from divein.models import Diver,Level,Federation,Graduate,Club,Spot,Dive,DiveTag,DivePart

class DiverAdmin(admin.ModelAdmin):
    fieldsets = [
        ('Personal', {'fields': ['user', 'birth_date']}),
        #('Diving'  , {'fields': ['levels']}),
    ]
    #What to display?
    
    #list_filter    = ['levels']


admin.site.register(Diver)
admin.site.register(Graduate)
admin.site.register(Level)
admin.site.register(Club)
admin.site.register(Dive)
admin.site.register(Spot)
admin.site.register(Federation)
admin.site.register(DiveTag)
admin.site.register(DivePart)

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/' , include(admin.site.urls)),
    url(r'^polls/' , include('polls.urls' , namespace='polls')),
    url(r'^divein/', include('divein.urls', namespace='divein')),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$'                       , views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$'           , views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$'   , views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$' , views.vote, name='vote'),
)

divein/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


import urllib, hashlib

class Federation(models.Model):
    federation = models.CharField('Federation name'    , max_length=50)
    website    = models.URLField('Federation website'  , blank=True)

    def __unicode__(self):
        return self.federation

class Level(models.Model):
    level      = models.CharField('The level name'      , max_length=50)
    federation = models.ForeignKey(Federation)

    def __unicode__(self):
        return u'{}({})'.format(self.level, self.federation)

class Club(models.Model):
    club      = models.CharField('The club name' , max_length=50)
    website   = models.URLField('Club website'  , blank=True)
    city      = models.CharField('Club city', max_length=50  , blank=True)

    def __unicode__(self):
        return self.club

class Diver(models.Model):
    #Do not refer directly User since it can change
    #User settings.AUTH_USER_MODEL instead
    user       = models.OneToOneField(settings.AUTH_USER_MODEL) 
    birth_date = models.DateField('birth_date')
    levels     = models.ManyToManyField(Level, through='Graduate')
    # self refer to Diver class, not current instance
    friends    = models.ManyToManyField('self', blank=True)

    def __unicode__(self):
        return u'{}'.format(self.user.username)

    def getGravatar(self, size=40):
        default = "http://www.example.com/default.jpg"
        gravatar_url = "http://www.gravatar.com/avatar/"
        gravatar_url += hashlib.md5(self.user.email.lower()).hexdigest() + "?"
        gravatar_url += urllib.urlencode({'d':default, 's':str(size)})
        return gravatar_url

class Graduate(models.Model):
    diver         = models.ForeignKey(Diver)
    level         = models.ForeignKey(Level)
    date          = models.DateField('The graduate date')
    club          = models.ForeignKey(Club, blank=True)

    def __unicode__(self):
        return u'{} => {}'.format(self.diver, self.level)

class Spot(models.Model):
    name     = models.CharField('The site name'     ,max_length=200)
    city     = models.CharField('The site city'     ,max_length=200)
    country  = models.CharField('The site country'  ,max_length=200)
    max_depth = models.IntegerField('Maximum site depth', blank = True)
    gps      = models.CharField('GPS location'     ,max_length=200, blank = True)
    
    def __unicode__(self):
        return u'{}'.format(self.name)

class SpotComment(models.Model):
    text    = models.CharField('Comment', max_length=1000)
    diver   = models.ForeignKey(Diver)
    date    = models.DateTimeField('Comment posted date')
    
    def __unicode__(self):
        return u'{} says {}'.format(self.diver, self.text)



class DiveTag(models.Model):
    tag          = models.CharField('The dive tag'     ,max_length=30)

    def __unicode__(self):
        return self.tag

class Dive(models.Model):
    date         = models.DateTimeField('Dive date')
    duration     = models.IntegerField('Dive duration in minutes')
    depth        = models.IntegerField('Dive max deep in meters')
    club         = models.ForeignKey(Club, blank=True)
    spot         = models.ForeignKey(Spot)
    created_by   = models.ForeignKey(Diver, related_name='+')
    created_date = models.DateField('Creation date')
    divers       = models.ManyToManyField(Diver, through='DivePart', related_name='+', blank=True)
    tags         = models.ManyToManyField(DiveTag, blank=True)

    def __unicode__(self):
        return u'{} [{}]'.format(self.spot, self.date)


class DivePart(models.Model):
    dive    = models.ForeignKey(Dive)
    diver   = models.ForeignKey(Diver)
    note    = models.IntegerField('The dive note')
    leader  = models.BooleanField('Was the dive leader')

    def __unicode__(self):
        return u'{} was in {}'.format(self.diver, self.dive)

divein/forms.py
from divein.models import Dive
from django.forms import ModelForm
from django import forms
from datetime  import date,time,datetime

class DiveForm(ModelForm):
    class Meta:
        model = Dive
        #In the future, remove created_by and created_date
        #exclude = ('created_by', 'created_date') 
        # exclude m2m relation with through attribute. Don't know how to do it for now
        exclude = ('divers') 

class DiveForm2(forms.Form):
    max_deep    = forms.DecimalField(min_value=0, max_value=70)
    length      = forms.IntegerField(min_value=0, max_value=240)
    time        = forms.TimeField(initial=datetime.now().time())
    date        = forms.DateField(initial=date.today())
    
    pass

divein/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic

from django.contrib.auth import logout
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from datetime import datetime

from divein.models import Diver,Dive,DivePart,Spot,Club
from divein.forms  import DiveForm, DiveForm2

def index(request):
    dives = Dive.objects.all()
    return render(request, 'divein/index.html', {'dives': dives})

class DiverListView(generic.ListView):
    model = Diver

class DiverDetailView(generic.DetailView):
    model = Diver

class SpotDetailView(generic.DetailView):
    model = Spot

class SpotListView(generic.ListView):
    model = Spot

@login_required(login_url='/divein/login')
def dive_detail(request, pk):
    dive 		= get_object_or_404(Dive, pk=pk)
    tags 		= dive.tags.all()
    dive_parts 	= DivePart.objects.filter(dive=dive)
    return render(request, 'divein/dive_detail.html', {'dive': dive, 'tags' : tags, 'dive_parts' : dive_parts})

@login_required(login_url='/divein/login')
def dive_form(request):
    if request.method == 'POST': # If the form has been submitted...
        form = DiveForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            form.save()
            return HttpResponseRedirect('/divein') # Redirect after POST to HOME
    else:
        form = DiveForm(initial = {'created_by' : request.user, 'created_date' : datetime.date.today})
    return render(request, 'divein/dive_form.html', {
        'form': form,
    })

@login_required(login_url='/divein/login')
def spot_add_dive(request, pk):
    """
    Adds a dive to an existing spot
    """
    spot  = get_object_or_404(Spot, pk=pk)
    if request.method == 'POST': # If the form has been submitted...
        form = DiveForm2(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            max_deep = form.cleaned_data['max_deep']
            length   = form.cleaned_data['length']
            time     = form.cleaned_data['time']   
            date     = form.cleaned_data['date']
            print('date is {} \ntime is {}'.format(date, time))
            #Create a new Dive
            d = Dive(
                date = datetime.combine(date, time),
                duration = length,
                depth      = max_deep,
                club        = get_object_or_404(Club, pk=1),
                spot        = spot,
                created_by  = request.user.diver,
                created_date = date.today(),
            )
            d.save()


            return HttpResponseRedirect('/divein/dive/{}'.format(d.id)) # Redirect after POST to created dive
    else:
        form = DiveForm2()
    return render(request, 'divein/spot_add_dive.html', {
        'form' : form,
        'spot' : spot,
    })


@login_required(login_url='/divein/login')
def profile(request):
    return render(request, 'divein/profile.html', {'gravatar' : request.user.diver.getGravatar(100)})

#Do not use logout bu logoutv to avoid infinite loop
@login_required(login_url='/divein/login')
def logoutv(request):
    logout(request)
    return render(request, 'divein/index.html')

divein/templates/divein/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>{% block title%}Dive#{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"    content="Le carnet de plongée du futur">
    <meta name="author"         content="Booba Skaya">

    <!-- Le styles -->
    <link href="{% static "/static/bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{% static "/static/bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "/static/bootstrap/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "/static/bootstrap/ico/apple-touch-icon-114-precomposed.png" %}">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "/static/bootstrap/ico/apple-touch-icon-72-precomposed.png" %}">
                    <link rel="apple-touch-icon-precomposed" href="{% static "/static/bootstrap/ico/apple-touch-icon-57-precomposed.png" %}">
                                   <link rel="shortcut icon" href="{% static "/static/bootstrap/ico/favicon.png" %}">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'divein:index' %}" title="Retour à l'accueuil">D#</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
                {% if user.is_authenticated %}
                    <i class="icon-user icon-white"></i> 
                    <a href="{% url 'divein:profile' %}" title="Mon profil"      class="navbar-link">{{ user.username }}</a>
                    |
                    <a href="{% url 'divein:logout' %}"  title="De deconnecter"  class="navbar-link"><i class="icon-eject icon-white"></i> </a>
                {% else %}
                    <a href="{% url 'divein:login' %}"   title="Me connected" class="navbar-link">Se connecter</a>        
                {% endif %}
            </p>
            <ul class="nav">
              <li><a href="{% url 'divein:divers'  %}">Plongeurs</a></li>
              <li><a href="{% url 'divein:spots'   %}">Spots</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Plongée <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'divein:dive_add' %}">Ajouter une plongée</a></li>
                  <li><a href="#">Voir mes plongées</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li><a href="#about"  >About</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Social</li>
              <!-- <li class="active"><a href="#">Link</a></li> -->
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Spots</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          {% block content %}
            <div class="hero-unit">
                <p>Put your content here.</p>
            </div>
          {% endblock %}
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>
      <footer>
        <p class="muted">BoobaSkaya</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="/static/bootstrap/js/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
  </body>
</html>

divein/templates/divein/dive_detail.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
<h1> #{{ dive.pk }} : {{ dive }}</h1>
<ul>
	<li>date : {{ dive.date }}</li>
    <li>duration : {{ dive.duration}}</li>
    <li>depth : {{ dive.depth}}</li>
    <li>club : {{ dive.club }}</li>
    <li>spot : {{ dive.spot }}</li>
    <li>created_by : {{ dive.created_by}}</li>
    <li>created_date : {{ dive.created_date}}</li>
    <li>divers : {% for dive_part in dive_parts %} {{ dive_part.diver }}{% if dive_part.leader%}(*){% endif %} {% endfor %}</li>
    <li>tags : {% for tag in dive.tags.all %} {{ tag }} {% endfor %}</li>
</ul>
{% endblock %}

divein/templates/divein/dive_form.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
<form action="{% url 'divein:dive_add' %}" method="post">{% csrf_token %}
{{ form.as_ul }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

divein/templates/divein/diver_detail.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
<h1> {{ diver.first_name }} {{ diver.last_name }} </h1>
<ul>
    <li>Name: {{ diver.firstname }} {{ diver.last_name }} {{ diver }}</li>
    <li>Email: {{ diver.email }}</li>
    <li>Birth: {{ diver.birth_date }}</li>
    <!-- {% for lvl in diver.levels_set_all %}
        <li>Level {{ forloop.counter }} : {{ lvl }}</li>
    {% endfor %} -->
</ul>
{% endblock %}

divein/templates/divein/diver_list.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
{% if diver_list %}
    <ul>
    {% for diver in diver_list %}
        <!-- Using url 'detail' will look in urls.py -->
        <li><a href="{% url 'divein:diver' diver.id %}">{{ diver }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No diver are available.</p>
{% endif %}
{% endblock %}

divein/templates/divein/index.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
    <p class="alert">Ce site est en construction hein :)</p>
    <table class="table  table-striped">
        <tr><th>#</th><th>Date</th><th>Spot</th></tr>
        {% for dive in dives %}
            <tr>
                <td><a href="{% url 'divein:dive' dive.id %}">{{ dive.pk }}</a></td>
                <td>{{ dive.date }}</td>
                <td><a href="{% url 'divein:spot' dive.spot.id %}">{{ dive.spot.name }}</a></td>    
            </tr>
        {% endfor %}
        <caption>Les dernières plongées</caption>
    </table>
{% endblock %}

divein/templates/divein/login.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}

{% block content %}

{% if form.errors %}
<p class="alert">Votre nom et/ou mot de passe ne correspondent pas. Veuillez réessayer</p>
{% endif %}

<form method="post" action="{% url 'divein:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>Nom d'utilisateur</td> <!-- {{ form.username.label_tag }} -->
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>Mot de passe</td><!-- {{ form.password.label_tag }} -->
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

divein/templates/divein/profile.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
    
    <h1>Profil de {{ user.username }}</h1>
    <div class="span2">
        <img src="{{ gravatar }}" alt="Gravatar" title="Gravatar"/>
    </div>
    <ul class="span6 unstyled">
        <li><i class="icon-calendar" title="Date de naissance"></i> : {{ user.diver.birth_date }}</li>
        <li><i class="icon-envelope" title="mail"></i> : <a href="mailto:{{ user.email }}">{{ user.email }}</a></li>
    </ul>

{% endblock %}

divein/templates/divein/spot_add_dive.html
{% extends "divein/base.html" %}

{% block title %}dive#add dive to spot {{ spot.id }}{% endblock %}
{% block content %}

on ajoute une plongée à {{ spot }}?

<form action="{% url 'divein:spot_add_dive' spot.id %}" method="post">{% csrf_token %}
{{ form.as_table}}
<br/>
<input type="submit" value="Submit" />
</form>
{% endblock %}

divein/templates/divein/spot_detail.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
<h1> #{{ spot.pk }} : {{ spot }}</h1>

<ul>
	<li> name: {{ spot.name }} </li>
	<li> city: {{ spot.city }} </li>
	<li> country: {{ spot.country }} </li>
	<li> max_depth: {{ spot.max_depth }} </li>
	<li> gps: {{ spot.gps }} </li>
</ul>
{% endblock %}

divein/templates/divein/spot_list.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
{% if spot_list %}
    <table class="table table-striped">
        <tr><th>+1</th><th>Spot</th><th>Ville</th><th>Prof Max</th></tr>
        {% for spot in spot_list %}
        <tr>
        <td><a href="{% url 'divein:spot_add_dive' spot.id %}" title="Ajouter une plongée sur ce spot" class="btn btn-success"><i class="icon-plus-sign icon-white"/> </a></td>
        <td><a href="{% url 'divein:spot' spot.id %}">{{ spot }}</a></td>
        <td>{{ spot.city }}</td>
        <td>{{ spot.max_depth }}</td>
        </tr>
        {% endfor %}
    <caption>La liste des spots de plongée</caption>
    </table>
{% else %}
    <p>No spots are available.</p>
{% endif %}
{% endblock %}

divein/templates/divein/user_detail.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
<h1> {{ user.first_name }} {{ user.last_name }} </h1>
<ul>
    <li>Name: {{ user.firstname }} {{ user.last_name }} {{ user }}</li>
    <li>Email: {{ user.email }}</li>
    <li>Birth: {{ user.birth_date }}</li>
    <!-- {% for lvl in user.levels_set_all %}
        <li>Level {{ forloop.counter }} : {{ lvl }}</li>
    {% endfor %} -->
</ul>
{% endblock %}

divein/templates/divein/user_list.html
{% extends "divein/base.html" %}

{% block title %}dive#{% endblock %}
{% block content %}
{% if user_list %}
    <ul>
    {% for user in user_list %}
        <!-- Using url 'detail' will look in urls.py -->
        <li><a href="{% url 'divein:diver' diver.id %}">{{ user }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}
{% endblock %}